---
- hosts: 172.31.8.202
  become: yes
  tasks:
  - include_tasks: myfiles.yml
  
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy index.html file into node side
    copy: 
      src: myindex.html
      dest: /var/www/html/index.html

  - name: copy my index.j2 file into node side
    template: 
         src: myindex.j2
         dest: /var/www/html/index.html
  - name: download internet file
    get_url:
        url: https://madhu13april22.s3.us-west-2.amazonaws.com/mahaLogin-2.0.war
        dest: /home/ubuntu/
        force_basic_auth: yes  